server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: personal-landing-page
  
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  
  web:
    resources:
      static-locations: classpath:/static/
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 日志配置
logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 